services:
  app:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "8765:8765"
    environment:
      PYTHONUTF8: "1"
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    volumes:
      - .:/app
    command: python -m app
